//*******************************************************************************
//* STY_PS_1Potion generated by Eliot.UELib using UE Explorer.
//* Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
//* http://eliotvu.com
//*
//* All rights belong to their respective owners.
//********************************************************************************
class STY_PS_1Potion extends STY_PS_PotionSelect
    instanced;

defaultproperties
{
    KeyName="SHPS_1Potion"
}