//*******************************************************************************
//* KWACTION_SayTo generated by Eliot.UELib using UE Explorer.
//* Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
//* http://eliotvu.com
//*
//* All rights belong to their respective owners.
//*******************************************************************************
class KWACTION_SayTo extends KWACTION_Say
    editinlinenew
    collapsecategories
    hidecategories(Object);
