//*******************************************************************************
//* ReActor generated by Eliot.UELib using UE Explorer.
//* Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
//* http://eliotvu.com
//*
//* All rights belong to their respective owners.
//*******************************************************************************
class ReActor extends ScriptedSequence
    editinlinenew
    collapsecategories
    hidecategories(Advanced,Collision,Display,Force,Karma,Lighting,LightColor,Movement,Sound,Events);

var() export editinline ReactionTrigger Key;

function Setup(Actor NewOwner);

function Tick(float fDeltaTime);

function PostBeginPlay();

defaultproperties
{
	Begin Object Class=ACTION_WaitForEvent Name=ACTION_WaitForEvent0
		ExternalEvent=Error
	End Object
    Actions(0)=ACTION_WaitForEvent0
    bHardAttach=true
    bCollideWhenPlacing=false
}